apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "patchwright.fullname" . }}-rules
  labels:
    {{- include "patchwright.labels" . | nindent 4 }}
data:
  ownership.yaml: |
    {{- .Values.config.ownership | nindent 4 }}
  policy.yaml: |
    {{- .Values.config.policy | nindent 4 }}
